### ISSUE TITLE
Is this unstable?

### ISSUE THREAD

**Issue by callumacrae** [scalableminds/gulp-gm#7]
Hey!

The current version of this project is 0.0.7. Is it actually in development, or is it done?

If it's done, it should be on 1.x as per [semver.org](http://semver.org/)

**Comment by normanrz** [comment]
I don't think this project has large enough adoption to tell whether it is really stable. Also, it is not as actively maintained as some other projects. So, I'd rather keep it on 0.x

**Comment by callumacrae** [comment]
We were using it on https://www.lostmy.name/ for quite a long time to generate our responsive images. We're now calling `gm` directly because we wanted to access a property on the vinyl file object and it wasn't possible when using gulp-gm, but when we used this plugin, we never had any problems with it :)
