### ISSUE TITLE
PNG -> JPG transparent fill color?

### ISSUE THREAD

**Issue by Jakobud** [scalableminds/gulp-gm#9]
If you have a PNG (with transparency) that you are converting to a JPG, the transparency gets filled with black by default. How can I specify the fill color?

Also, I'm using `gulp-image-resize` with `gulp-gm`. It's when I resize a PNG and convert it to JPG that the problem happens. What do I need to do here?

**Comment by normanrz** [comment]
Hi, according to [this forum post](http://www.imagemagick.org/discourse-server/viewtopic.php?t=11398) you should be able to control it with something like:
```
return gmfile
  .fill("white")
  .opaque("none")
  .format("jpg");
```
I'm afraid you can't control this directly in `gulp-image-resize`. But you could first run your images through `gulp-gm` to convert them to jpg, before resizing them. Might not be the most performant option but saves some code ;-)
